version: '3'
services:
  php:
    build: ./LaravelApp/
    volumes:
      - ./LaravelApp/:/var/www/html
    ports:
      - '8000:8000'
    depends_on:
      - database
  rails5:
    build: ./RailsApp/
    environment:
      RAILS_ENV: development
      TZ: Asia/Tokyo
    ports:
      - '3000:3000'
    volumes:
      - ./RailsApp/:/usr/src/app
    depends_on:
      - database
  database:
    image: mysql:8.0.14
    environment:
       MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --default-authentication-plugin=mysql_native_password
volumes:
  mysql-data:
    driver: local